# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [(modulesPath + "/installer/scan/not-detected.nix")];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelPackages = pkgs.linuxKernel.packages.linux_6_1;
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [];

  # Root Parition
  fileSystems."/" = { 
    device = "/dev/disk/by-uuid/4e8f9cfc-9a2c-40e7-ad01-00a575e85c77";
    fsType = "ext4";
  };

  # ESP Partition
  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/140D-841F";
    fsType = "vfat";
  };

  # Swap Parition(s)
  swapDevices = [{
    device = "/dev/disk/by-uuid/961d33dc-893a-4661-b8eb-77528d78f022";
  }];


  # Hardware
  hardware = {

    # CPU / AMD Microcode
    cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

    # Video (high-resolution display)
    video.hidpi.enable = lib.mkDefault true;

    # Bluetooth
    bluetooth = {
      enable = true;
      package = pkgs.bluezFull;
      powerOnBoot = true;
      settings = {
        General = {
          Enable = "Source,Sink,Media,Socket";
        };
      };
    };

    # Pulseaudio
    pulseaudio = {
      enable = false;
      support32Bit = true;
      package = pkgs.pulseaudioFull;
    };
  };
}
