name: 'CI/CD'
on:
  pull_request:
  push:
    branches:
     - 'master'
     - 'release/*'
     - 'feature/*'

jobs:
  # NixOS
  Linux:
    name: 'NixOS (x86_64)'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Check Nix Flake Inputs
      uses: DeterminateSystems/flake-checker-action@v4
    
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v3

    - name: Free VM Disk Space
      run: scripts/free_disk_space.sh
    
    - name: Build NixOS Flake
      run: nix build '.#nixosConfigurations.AMZ-Linux.config.system.build.toplevel'
    
    - name: Show Build Ouput
      run: ls -l result*

    - name: Vulnix Report
      run: (pipx run vulnix ./result || true) > report.json
    
    - name: Upload Vulnix Report Artifact
      uses: actions/upload-artifact@v3
      with:
        name: vulnix-nixos-report
        path: report.json
