name: "Test"
on:
  pull_request:
  push:
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    # - uses: cachix/cachix-action@v11
    #   with:
    #     name: mycache
    #     # If you chose signing key for write access
    #     signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    #     # If you chose API tokens for write access OR if you have a private cache
    #     authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build --flake ./#AMZ-Linux
    - run: nix-shell --run "echo Done"
  darwin:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-build --flake ./#AMZ-MacBook
    - run: nix-shell --run "echo Done"
    # - uses: cachix/cachix-action@v11
    #   with:
    #     name: mycache
    #     # If you chose signing key for write access
    #     signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    #     # If you chose API tokens for write access OR if you have a private cache
    #     authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
   
