name: "Test"
on:
  pull_request:
  push:
    branches:
     - master

jobs:
  # NixOS
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix build '.#nixosConfigurations.AMZ-Linux.config.system.build.toplevel' --print-out-paths
    - run: ls -l result*
  
  # Nix Darwin
  Darwin:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix build '.#darwinConfigurations.AMZ-MacBook.config.system.build.toplevel' --print-out-paths
    - run: ls -l result*
   
